import Link from 'next/link'

import '../styles/globals.scss'
import headerStyle from '../styles/header.module.scss'
import footerStyle from '../styles/footer.module.scss'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className={headerStyle.navigation}>
            <Link href="/" className={headerStyle.initials}>
              <div className={headerStyle.name}>Lukas</div><div className={headerStyle.surname}> Stavaris</div>
            </Link>
            <Link href="/about" className={headerStyle.about}>
              <span >ABOUT</span>
            </Link>
            <Link href="/test" className={headerStyle.test}>
              <span >TEST</span>
            </Link>
          </nav>
        </header>
        {children}
        <footer>
          aaa
        </footer>
      </body>
    </html>
  )
}
